### ISSUE TITLE
Doesn't work on Node 12.x because of imports

### ISSUE THREAD

**Issue by RauliL** [chalk/strip-ansi-cli#3]
When trying to run this with Node v12.14.1, an syntax error is thrown because [cli.js](https://github.com/chalk/strip-ansi-cli/blob/449a1bb08b660969dfa16b6b3116190c3de32c81/cli.js) uses import statements instead of `require()`, which is apparently supported from Node version 13 and upwards, yet the [package.json](https://github.com/chalk/strip-ansi-cli/blob/449a1bb08b660969dfa16b6b3116190c3de32c81/package.json#L17-L19) specifies version 12 to be supported.

**Comment by Qix-** [comment]
@sindresorhus @RauliL is correct, and [this comment](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#gistcomment-3723336) is probably the right move IMO. I'd actually go so far as to suggest `12.22.0` since that's when the official docs state that it is generally and stabily supported.

In any case, `>=12` is not right - I agree.

---

@RauliL, if you can't upgrade to `>= 13`, perhaps you can upgrade to `12.22` instead? That will solve your issue without needing to upgrade to 13.

**Comment by RauliL** [comment]
I can upgrade but I just wanted to point out that the engine requirement in `package.json` was incorrect.
